# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_um', models.IntegerField()),
                ('cedula_dois', models.IntegerField()),
                ('cedula_cinco', models.IntegerField()),
                ('cedula_dez', models.IntegerField()),
                ('cedula_vinte', models.IntegerField()),
                ('cedula_cinquenta', models.IntegerField()),
                ('cedula_cem', models.IntegerField()),
            ],
        ),
    ]
