# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170714_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('quantiade', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='cedula_cem',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='cedula_cinco',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='cedula_cinquenta',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='cedula_dez',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='cedula_dois',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='cedula_um',
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='cedula_vinte',
        ),
        migrations.AddField(
            model_name='cedula',
            name='caixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cedulas', to='core.Caixa'),
        ),
    ]
