# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170714_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cedula',
            old_name='quantiade',
            new_name='quantidade',
        ),
    ]
