# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170714_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
