# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170714_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_antes', models.IntegerField()),
                ('saldo_depois', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='core.Conta')),
            ],
        ),
    ]
